const fs=require('fs-extra');
const path=require('path');
const postsDir=path.join(__dirname,'posts');
fs.ensureDirSync(postsDir);
const apiKey=process.env.GEMINI_API_KEY;
const model=process.env.GEMINI_MODEL||'gemini-3.8-flash';
const fallbackModels=[model,'gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash','gemini-3.5-flash-lite'].filter((v,i,a)=>v&&a.indexOf(v)===i);

// US-focused editorial plan. Each topic is assigned to one navigation category.
const usTopics=[
['Deep Cleaning','How to Get Hard Water Stains Off Glass Shower Doors'],['Deep Cleaning','How to Remove Grease From Kitchen Cabinets Without Damaging the Finish'],['Deep Cleaning','How to Clean Grout Without Damaging Tile'],['Deep Cleaning','How to Remove Oil Stains From a Concrete Driveway'],['Deep Cleaning','How to Clean a Microwave Without Harsh Chemicals'],['Deep Cleaning','How to Remove Red Wine Stains From Carpet'],['Deep Cleaning','How to Clean Baseboards Without Damaging Painted Walls'],['Deep Cleaning','How to Remove Soap Scum From a Bathtub'],['Deep Cleaning','How to Clean Window Tracks and Sliding Door Tracks'],['Deep Cleaning','How to Clean a Glass Stovetop Without Scratches'],
['Home Organization','Small Kitchen Pantry Organization Ideas That Actually Save Space'],['Home Organization','How to Organize Under the Kitchen Sink Without the Clutter'],['Home Organization','How to Declutter a Messy Closet Fast'],['Home Organization','Small Apartment Storage Ideas for Renters'],['Home Organization','How to Organize a Bathroom With Almost No Counter Space'],['Home Organization','How to Create a Simple Entryway Drop Zone'],['Home Organization','How to Organize Cleaning Supplies Safely at Home'],['Home Organization','How to Organize a Refrigerator for Less Food Waste'],['Home Organization','How to Organize a Garage When You Have Limited Space'],['Home Organization','A Practical 30-Day Decluttering Plan for Busy Families'],
['Green & DIY','How to Make a Simple DIY All-Purpose Cleaner Safely'],['Green & DIY','Non-Toxic Bathroom Cleaner DIY: What Actually Works'],['Green & DIY','Eco-Friendly Pet Stain Removal for Carpets and Rugs'],['Green & DIY','How to Reduce Single-Use Plastic in Your Cleaning Routine'],['Green & DIY','Microplastic-Free Cleaning Tools: What to Look For'],['Green & DIY','How to Clean With Castile Soap Without Making Common Mistakes'],['Green & DIY','How to Make a DIY Glass Cleaner Without Streaks'],['Green & DIY','Natural Ways to Freshen a Musty Room Without Heavy Fragrance'],['Green & DIY','How to Reuse Old Towels as Low-Waste Cleaning Cloths'],['Green & DIY','What Makes a Cleaning Product More Eco-Friendly? A Practical Guide'],
['Appliance Care','How to Deep Clean a Ninja Air Fryer Safely'],['Appliance Care','How to Clean a Dishwasher Filter and Fix Common Odors'],['Appliance Care','How to Descale a Coffee Maker and Remove Mineral Buildup'],['Appliance Care','Dishwasher Spray Arm Clog Fix: A Step-by-Step Guide'],['Appliance Care','How to Clean a Front-Load Washer and Remove Musty Odors'],['Appliance Care','How to Clean a Refrigerator Inside and Prevent Odors'],['Appliance Care','How to Clean Stainless Steel Appliances Without Streaks'],['Appliance Care','How to Clean a Vacuum Cleaner and Its Filters'],['Appliance Care','How to Clean a Bathroom Exhaust Fan Safely'],['Appliance Care','How to Clean an Oven Without Damaging the Finish'],
['Odor & Maintenance','How to Get Rid of Dog Smell in a Couch'],['Odor & Maintenance','How to Get Rid of Drain Odors Naturally and Safely'],['Odor & Maintenance','Why Does My House Smell? Common Causes and Fixes'],['Odor & Maintenance','How to Clean a Washing Machine to Stop Musty Smells'],['Odor & Maintenance','How to Remove Moldy Smells From a Bathroom Safely'],['Odor & Maintenance','How to Stop Garbage Disposal Odors From Coming Back'],['Odor & Maintenance','How to Reduce Dust Around HVAC Vents and Registers'],['Odor & Maintenance','How to Prevent Musty Smells in a Basement'],['Odor & Maintenance','How to Freshen a Pet-Friendly Home Without Overpowering Fragrance'],['Odor & Maintenance','Secret Places in Your Home You Should Clean More Often']
];

function slugify(v){return String(v).toLowerCase().trim().replace(/[^a-z0-9\\s-]/g,'').replace(/\\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');}
async function existingPosts(){const files=(await fs.readdir(postsDir)).filter(f=>f.endsWith('.json'));const posts=[];for(const f of files){try{posts.push(await fs.readJson(path.join(postsDir,f)));}catch{}}return posts;}
function imageQuery(topic,category){const t=topic.toLowerCase();const map=[
[/hard water|shower doors/,'hard water stains glass shower door cleaning'],[/grease.*cabinets/,'greasy kitchen cabinets deep cleaning'],[/grout/,'tile grout deep cleaning'],[/oil stains.*driveway/,'concrete driveway oil stain cleaning'],[/microwave/,'microwave cleaning kitchen'],[/red wine.*carpet/,'red wine carpet stain removal'],[/baseboards/,'baseboard deep cleaning home'],[/soap scum|bathtub/,'bathtub soap scum cleaning'],[/window tracks/,'window track cleaning'],[/glass stovetop/,'glass cooktop cleaning'],[/pantry/,'organized kitchen pantry storage'],[/under.*sink/,'under kitchen sink organization'],[/closet/,'closet decluttering organization'],[/apartment storage/,'small apartment storage organization'],[/bathroom.*counter/,'small bathroom organization'],[/entryway/,'organized home entryway'],[/cleaning supplies/,'organized cleaning supplies cabinet'],[/refrigerator.*food waste/,'organized refrigerator food storage'],[/garage/,'garage organization storage'],[/decluttering/,'home decluttering organization'],[/all-purpose cleaner|bathroom cleaner|glass cleaner/,'eco friendly DIY home cleaner'],[/pet stain/,'eco friendly pet stain carpet cleaning'],[/plastic/,'zero waste cleaning supplies home'],[/microplastic/,'plastic free cleaning tools'],[/castile/,'castile soap cleaning'],[/musty room/,'fresh clean room natural home'],[/towels/,'reusable cleaning cloths towels'],[/eco-friendly/,'eco friendly cleaning products home'],[/air fryer/,'Ninja air fryer cleaning'],[/dishwasher filter|spray arm/,'dishwasher filter cleaning appliance'],[/coffee maker/,'coffee maker descaling cleaning'],[/front-load washer|washing machine/,'front load washing machine cleaning'],[/stainless steel/,'stainless steel appliance cleaning'],[/vacuum cleaner/,'vacuum cleaner filter cleaning'],[/exhaust fan/,'bathroom exhaust fan cleaning'],[/oven/,'oven deep cleaning appliance'],[/dog smell|pet-friendly/,'dog odor couch pet friendly home cleaning'],[/drain odors/,'drain odor home maintenance'],[/house smell/,'home odor troubleshooting cleaning'],[/garbage disposal/,'garbage disposal cleaning odor'],[/HVAC vents|dust.*HVAC/,'HVAC vent dust cleaning home'],[/basement/,'basement musty odor prevention'],[/secret places/,'often forgotten home cleaning spots']
];return (map.find(([re])=>re.test(t))||[null,`${category} home care cleaning`])[1];}
async function searchImage(topic,category){const key=process.env.SERPAPI_KEY;if(!key)return null;const q=encodeURIComponent(imageQuery(topic,category));const r=await fetch(`https://serpapi.com/search.json?engine=google_images&q=${q}&safe=active&api_key=${encodeURIComponent(key)}`);if(!r.ok)return null;const d=await r.json();const blocked=/instagram|facebook|pinterest|tiktok/i;const results=(d.images_results||[]).filter(x=>!blocked.test(`${x.source||''} ${x.link||''}`)&&/^https:\/\//.test(x.original||'')&&/\\.(jpg|jpeg|png|webp)(\\?|$)/i.test(x.original||''));if(!results.length)return null;const x=results[0];return{url:x.original,source:x.source||'Image source',source_url:x.link||'',credit:x.title||'',license:'Verify image license at source before publishing',license_url:x.link||''};}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function transient(s){return[429,500,502,503,504].includes(s);}
async function requestGemini(prompt){let last='';for(const current of fallbackModels){for(let attempt=1;attempt<=2;attempt++){const r=await fetch('https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:current,temperature:.7,messages:[{role:'system',content:'You are an experienced US home and lifestyle SEO editor. Write useful, accurate, original content. Never invent statistics or citations.'},{role:'user',content:prompt}]})});if(r.ok){const d=await r.json();const raw=d.choices?.[0]?.message?.content?.trim();if(raw)return raw;}else{last=`${r.status} ${await r.text()}`;if(!transient(r.status))throw Error(`Gemini API error: ${last}`);if(attempt<2)await sleep(4000*attempt);}}}throw Error(`Gemini API unavailable: ${last}`);}

async function generatePost(topic,category,titles){if(!apiKey)throw Error('GEMINI_API_KEY is not configured');const prompt=`Create one original 1,800-2,100 word article for a US Home & Living publication. Topic: ${topic}. Required navigation category: ${category}. Audience: US homeowners and renters.\n\nMake the article genuinely useful and search-intent focused. Target natural US long-tail queries and featured snippets without keyword stuffing.\n\nStructure: title; quick answer; why the problem happens when relevant; Materials Needed; Step-by-Step Instructions; What NOT to Do; Safety and Material Warnings; Maintenance Tips; FAQ. Use concise numbered steps and bullets where helpful.\n\nReturn at least 8 natural SEO keyword phrases. Include the exact search intent, close variants, and related long-tail queries.\n\nUS context: use US measurements and terminology. Naturally address relevant details such as renters/apartments, hard water, common US surfaces, HVAC vents, garbage disposals, or widely available US retail cleaning products. Do not force products into unrelated articles.\n\nSafety: never recommend mixing bleach with ammonia, acids, vinegar, toilet cleaner, or other cleaners. Warn about ventilation, labels, natural stone, delicate finishes, and abrasives when relevant.\n\nDo not promote Mr Glowra and do not mention this prompt. No fake citations. No medical or legal claims.\n\nReturn ONLY valid JSON with exactly title, description, category, keywords, content. Category MUST be exactly "${category}". Content must be plain text with headings but no Markdown markers, HTML, or bold syntax. Description must be <=160 characters.\n\nDo not repeat these existing titles: ${titles.join(' | ')||'none'}.`;
const raw=await requestGemini(prompt);let a;try{a=JSON.parse(raw.replace(/^```json\\s*/i,'').replace(/\\s*```$/i,''));}catch(e){throw Error(`Invalid Gemini JSON: ${e.message}`);}if(!a.title||!a.description||!a.content)throw Error('Generated article missing required fields');if(titles.some(t=>String(t).trim().toLowerCase()===String(a.title).trim().toLowerCase()))throw Error('Generated title duplicates an existing article');a.category=category;a.keywords=Array.isArray(a.keywords)?[...new Set(a.keywords.map(String).map(x=>x.trim()).filter(Boolean))].slice(0,12):[];if(a.keywords.length<8)a.keywords=[...new Set([...a.keywords,topic,`how to ${topic.toLowerCase().replace(/^how to\\s+/i,'')}`,category,'home cleaning tips'])].slice(0,10);const date=new Date().toISOString().slice(0,10);let slug=slugify(a.title)||slugify(topic);let file=path.join(postsDir,`${date}-${slug}.json`);if(await fs.pathExists(file))file=path.join(postsDir,`${date}-${slug}-${Date.now()}.json`);const image=await searchImage(a.title,category);const content=String(a.content).replace(/^#{1,6}\\s+/gm,'').replace(/\\*\\*(.*?)\\*\\*/g,'$1').replace(/\\r/g,'').trim();const post={title:String(a.title).trim(),description:String(a.description).trim().slice(0,160),category,keywords:a.keywords,content,slug,date,market:'US',image:image?.url||'',imageAlt:`${String(a.title).trim()} - relevant ${category.toLowerCase()} photo`,image_source:image?.source||'',image_source_url:image?.source_url||'',image_credit:image?.credit||'',image_license:image?.license||'',image_license_url:image?.license_url||''};await fs.writeJson(file,post,{spaces:2});console.log(`Created ${file} [${category}]${image?' with relevant image':''}`);}

(async()=>{const posts=await existingPosts();const titles=posts.map(p=>p.title).filter(Boolean);const used=new Set(posts.map(p=>slugify(p.title||'')));const count=Math.max(1,Number(process.env.BLOG_BATCH_SIZE||1));const selected=usTopics.filter(([cat,topic])=>!used.has(slugify(topic))).slice(0,count);if(!selected.length)throw Error('All planned US SEO topics have already been published.');let ok=0;for(const [category,topic] of selected){console.log(`Selected ${category}: ${topic}`);try{await generatePost(topic,category,titles);titles.push(topic);ok++;}catch(e){console.error(`FAILED ${topic}: ${e.stack||e}`);}}console.log(`US SEO batch complete: ${ok}/${selected.length}`);if(!ok)process.exit(1);})().catch(e=>{console.error(e);process.exit(1);});
