const express = require('express');
const fs = require('fs-extra');
const path = require('path');
const cors = require('cors');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public'), { extensions: ['html'] }));

const postsDir = path.join(__dirname, 'posts');
const SITE_URL = (process.env.SITE_URL || 'https://blog.mrglowra.com').replace(/\/$/, '');
const BRAND_URL = 'https://www.mrglowra.com';
const BRAND_NAME = 'Mr Glowra Pvt Ltd';

fs.ensureDirSync(postsDir);

function escapeHtml(value = '') { return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
function slugify(value = '') { return String(value).toLowerCase().trim().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, ''); }
function stripMarkup(value = '') { return String(value).replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim(); }
function postUrl(slug) { return `${SITE_URL}/blog/${encodeURIComponent(slug)}`; }

async function getPosts() {
  const files = (await fs.readdir(postsDir)).filter(file => file.endsWith('.json'));
  const posts = [];
  for (const file of files) {
    try { const data = await fs.readJson(path.join(postsDir, file)); posts.push({ ...data, slug: data.slug || slugify(data.title || file.replace(/\.json$/, '')), date: data.date || new Date().toISOString().slice(0, 10) }); }
    catch { console.warn(`Skipping invalid post: ${file}`); }
  }
  return posts.sort((a, b) => new Date(b.date) - new Date(a.date));
}

function layout({ title, description, canonical, content, type = 'website', schema = null }) {
  const safeDescription = stripMarkup(description).slice(0, 160);
  const jsonLd = schema ? `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(safeDescription)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${escapeHtml(canonical)}"><meta property="og:type" content="${escapeHtml(type)}"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(safeDescription)}"><meta property="og:url" content="${escapeHtml(canonical)}"><meta property="og:site_name" content="Mr Glowra"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escapeHtml(title)}"><meta name="twitter:description" content="${escapeHtml(safeDescription)}"><link rel="alternate" type="application/rss+xml" title="Mr Glowra Journal RSS" href="${SITE_URL}/feed.xml"><style>
:root{--ink:#17201b;--muted:#647067;--line:#e6ebe7;--brand:#176b3a;--soft:#f5f8f5}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:#fff}a{color:inherit;text-decoration:none}.nav{position:sticky;top:0;z-index:10;background:rgba(255,255,255,.95);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.nav-inner{max-width:1120px;margin:auto;padding:16px 22px;display:flex;align-items:center;justify-content:space-between;gap:20px}.logo{font-weight:900;font-size:1.2rem;letter-spacing:-.03em;color:var(--brand)}.nav a{font-size:.92rem;color:#435048;margin-left:18px}.hero{background:linear-gradient(135deg,#f2f8f3,#fff);border-bottom:1px solid var(--line)}.hero-inner{max-width:1120px;margin:auto;padding:72px 22px 64px}.eyebrow{color:var(--brand);font-weight:800;text-transform:uppercase;letter-spacing:.12em;font-size:.76rem}h1{font-size:clamp(2.3rem,6vw,4.5rem);line-height:1.02;letter-spacing:-.055em;max-width:850px;margin:14px 0 18px}.hero p{max-width:680px;color:var(--muted);font-size:1.08rem;line-height:1.7}.wrap{max-width:1120px;margin:auto;padding:44px 22px 80px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.card{border:1px solid var(--line);border-radius:20px;overflow:hidden;background:#fff;transition:transform .2s ease,box-shadow .2s ease}.card:hover{transform:translateY(-3px);box-shadow:0 14px 35px rgba(20,50,30,.08)}.card-body{padding:24px}.tag{display:inline-block;background:var(--soft);color:var(--brand);border-radius:999px;padding:6px 10px;font-size:.75rem;font-weight:800}.card h2{font-size:1.25rem;line-height:1.25;margin:14px 0 10px}.date{color:var(--muted);font-size:.84rem}.excerpt{color:#59645d;line-height:1.65}.article{max-width:780px;margin:auto}.article h1{max-width:none;font-size:clamp(2.2rem,5vw,3.8rem)}.article-content{color:#37423b;font-size:1.08rem;line-height:1.85;white-space:pre-wrap}.cta{margin-top:42px;padding:28px;border-radius:20px;background:var(--soft)}.btn{display:inline-block;margin-top:10px;padding:12px 18px;border-radius:999px;background:var(--brand);color:#fff;font-weight:800}.related{margin-top:48px;padding-top:30px;border-top:1px solid var(--line)}.related-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.related-card{padding:18px;border:1px solid var(--line);border-radius:16px}.related-card h3{margin:8px 0;font-size:1rem}footer{border-top:1px solid var(--line);padding:28px 22px;color:var(--muted);text-align:center;font-size:.9rem}footer a{color:var(--brand);font-weight:700}@media(max-width:800px){.grid{grid-template-columns:1fr}.related-grid{grid-template-columns:1fr}.nav-inner{padding:14px 16px}.nav a{margin-left:10px}.hero-inner{padding:52px 18px}.wrap{padding:32px 18px 60px}}
</style>${jsonLd}</head><body><nav class="nav"><div class="nav-inner"><a class="logo" href="${SITE_URL}/">Mr Glowra Journal</a><div><a href="${SITE_URL}/">Blog</a><a href="${BRAND_URL}">Mr Glowra</a></div></div></nav>${content}<footer>© ${new Date().getFullYear()} ${BRAND_NAME} · <a href="${BRAND_URL}">Power That Shines!</a></footer></body></html>`;
}

app.get('/health', (req, res) => res.json({ status: 'ok', service: 'mrglowra-blog' }));
app.get('/posts', async (req, res) => { try { res.json(await getPosts()); } catch { res.status(500).json({ error: 'Failed to read posts' }); } });
app.get('/feed.xml', async (req, res) => { const posts = await getPosts(); const items = posts.slice(0,20).map(post => `<item><title>${escapeHtml(post.title)}</title><link>${escapeHtml(postUrl(post.slug))}</link><guid>${escapeHtml(postUrl(post.slug))}</guid><pubDate>${new Date(post.date).toUTCString()}</pubDate><description>${escapeHtml(post.description || stripMarkup(post.content).slice(0,300))}</description></item>`).join(''); res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Mr Glowra Journal</title><link>${SITE_URL}/</link><description>Cleaning tips, home-care advice and product knowledge from Mr Glowra.</description>${items}</channel></rss>`); });
app.get('/sitemap.xml', async (req,res) => { const posts=await getPosts(); const urls=[`<url><loc>${SITE_URL}/</loc></url>`,...posts.map(post=>`<url><loc>${escapeHtml(postUrl(post.slug))}</loc><lastmod>${escapeHtml(post.date)}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url>`),`<url><loc>${SITE_URL}/feed.xml</loc></url>`]; res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.join('')}</urlset>`); });
app.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /posts\nSitemap: ${SITE_URL}/sitemap.xml\n`));
app.get('/blog/:slug',async(req,res)=>{const posts=await getPosts();const post=posts.find(item=>item.slug===req.params.slug);if(!post)return res.status(404).send(layout({title:'Article Not Found | Mr Glowra',description:'The requested article could not be found.',canonical:`${SITE_URL}/blog/${escapeHtml(req.params.slug)}`,content:'<main class="wrap"><div class="article"><h1>Article not found</h1><p>Return to the <a href="/">Mr Glowra Journal</a>.</p></div></main>'}));const description=post.description||stripMarkup(post.content).slice(0,155);const related=posts.filter(item=>item.slug!==post.slug&&item.category===post.category).slice(0,2);const fallbackRelated=related.length?related:posts.filter(item=>item.slug!==post.slug).slice(0,2);const relatedHtml=fallbackRelated.length?`<section class="related"><h2>More from the journal</h2><div class="related-grid">${fallbackRelated.map(item=>`<a class="related-card" href="${postUrl(item.slug)}"><span class="tag">${escapeHtml(item.category||'Cleaning Tips')}</span><h3>${escapeHtml(item.title)}</h3><span class="date">${escapeHtml(item.date)}</span></a>`).join('')}</div></section>`:'';const schema={'@context':'https://schema.org','@type':'Article',headline:post.title,description,datePublished:post.date,dateModified:post.date,keywords:Array.isArray(post.keywords)?post.keywords.join(', '):undefined,author:{'@type':'Organization',name:BRAND_NAME,url:BRAND_URL},publisher:{'@type':'Organization',name:BRAND_NAME,url:BRAND_URL},mainEntityOfPage:{'@type':'WebPage','@id':postUrl(post.slug)}};const content=`<main class="wrap"><article class="article"><span class="eyebrow">${escapeHtml(post.category||'Mr Glowra Journal')}</span><h1>${escapeHtml(post.title)}</h1><div class="date">Published ${escapeHtml(post.date)}</div><div class="article-content">${escapeHtml(post.content||'')}</div>${relatedHtml}<div class="cta"><strong>Explore Mr Glowra</strong><p>Learn more about our cleaning products and the Mr Glowra brand.</p><a class="btn" href="${BRAND_URL}">Visit Mr Glowra</a></div></article></main>`;res.send(layout({title:`${post.title} | Mr Glowra`,description,canonical:postUrl(post.slug),content,type:'article',schema}));});
app.get('/',async(req,res)=>{try{const posts=await getPosts();const cards=posts.map(post=>`<article class="card"><div class="card-body"><span class="tag">${escapeHtml(post.category||'Cleaning Tips')}</span><h2><a href="${postUrl(post.slug)}">${escapeHtml(post.title)}</a></h2><div class="date">${escapeHtml(post.date)}</div><p class="excerpt">${escapeHtml(post.description||stripMarkup(post.content).slice(0,150))}</p><a class="btn" href="${postUrl(post.slug)}">Read article</a></div></article>`).join('');const schema={'@context':'https://schema.org','@type':'Blog','name':'Mr Glowra Journal','url':SITE_URL,'description':'Cleaning tips, home-care advice and product knowledge from Mr Glowra.','publisher':{'@type':'Organization','name':BRAND_NAME,'url':BRAND_URL}};const content=`<header class="hero"><div class="hero-inner"><div class="eyebrow">Mr Glowra Journal</div><h1>Smarter cleaning. Better living.</h1><p>Practical cleaning tips, product knowledge and useful home-care ideas from Mr Glowra — Made in Uttarakhand.</p></div></header><main class="wrap"><div class="grid">${cards||'<p>No articles published yet.</p>'}</div></main>`;res.send(layout({title:'Mr Glowra Blog | Cleaning Tips & Home Care',description:'Cleaning tips, home-care advice and product knowledge from Mr Glowra.',canonical:SITE_URL,content,schema}));}catch{res.status(500).send('Failed to load blog.');}});

const PORT=process.env.PORT||3000;app.listen(PORT,'0.0.0.0',()=>console.log(`Mr Glowra Blog running on port ${PORT}`));
